local lush = require('lush')
local palette = require('lua.darcula-solid.palette')

---@diagnostic disable: undefined-global
return lush(function(injected_functions)
  local sym = injected_functions.sym

  return {
    -- Neovim highlight groups (see :h highlight-groups)
    Normal { fg = palette.subtle_white, bg = palette.black },
    ColorColumn { bg = palette.subtle_black },
    Conceal { fg = palette.gray },
    Cursor { fg = palette.black, bg = palette.white },
    lCursor { Cursor },
    CursorIM { Cursor },
    CurSearch { bg = palette.green },
    CursorColumn { bg = palette.subtle_black },
    CursorLine { CursorColumn },
    Directory { fg = palette.teal },
    DiffAdd { bg = palette.green },
    DiffChange { bg = palette.subtle_yellow },
    DiffDelete { bg = palette.red },
    DiffText { bg = palette.subtle_teal },
    DiffTextChange { bg = palette.subtle_teal },
    EndOfBuffer { Conceal },
    TermCursor { Cursor },
    TermCursorNC { Cursor },
    ErrorMsg { fg = palette.red },
    VertSplit { fg = palette.lightgray },
    Folded { fg = palette.lightgray, bg = palette.subtle_black },
    FoldColumn { fg = palette.gray },
    SignColumn { FoldColumn },
    IncSearch { CurSearch },
    Substitute { CurSearch },
    LineNr { fg = palette.gray },
    LineNrAbove { LineNr },
    LineNrBelow { LineNr },
    CursorLineNr { fg = palette.orange },
    CursorLineFold { LineNr },
    CursorLineSign { LineNr },
    MatchParen { fg = palette.white, bg = palette.subtle_black },
    ModeMsg { fg = palette.gray },
    MsgArea { bg = palette.subtle_black },
    MsgSeparator { fg = palette.orange },
    MoreMsg { fg = palette.subtle_green },
    NonText { bg = palette.subtle_black },
    NormalFloat { bg = palette.subtle_black },
    FloatBorder { VertSplit, bg = palette.subtle_black },
    FloatTitle { gui = 'bold' },
    NormalNC { Normal },
    Pmenu { bg = palette.subtle_black },
    PmenuSel { fg = palette.white_subtle, bg = palette.gray, gui = 'bold' },
    PmenuKind { Pmenu },
    PmenuKindSel { PmenuSel },
    PmenuExtra { Pmenu },
    PmenuExtraSel { PmenuSel },
    PmenuSbar { bg = palette.subtle_white, fg = palette.black },
    PmenuThumb { PmenuSbar },
    Question { fg = palette.subtle_green },
    QuickFixLine { fg = palette.white },
    Search { CurSearch },
    SpecialKey { Conceal },
    SpellBad { sp = palette.red, gui = "undercurl" },
    SpellCap { sp = palette.magenta, gui = "undercurl" },
    SpellLocal { sp = palette.orange, gui = "undercurl" },
    SpellRare { sp = palette.yellow, gui = "undercurl" },
    StatusLine { bg = palette.subtle_black },
    StatusLineNC { StatusLine },
    TabLine { StatusLine },
    TabLineFill { StatusLine },
    TabLineSel { PmenuSel },
    Title { fg = palette.blue },
    Visual { fg = palette.white, bg = palette.blue },
    VisualNOS { Visual },
    WarningMsg { fg = palette.red },
    Whitespace { Conceal },
    Winseparator { VertSplit },
    WildMenu { Pmenu },
    WinBar { fg = palette.gray, bg = palette.subtle_black },
    WinBarNC { WinBar },

    -- vim highlight groups (see :h group-name)
    Comment { fg = palette.lightgray, gui = "italic" },
    Constant { fg = palette.orange },
    String { fg = palette.subtle_green },
    Character { Constant },
    Number { fg = palette.blue },
    Boolean { Constant },
    Float { Number },
    Identifier { fg = palette.yellow },
    Function { fg = palette.yellow },
    Statement { Constant },
    Conditional { Constant },
    Repeat { Constant },
    Label { Constant },
    Operator { fg = palette.subtle_white },
    Keyword { Constant },
    Exception { fg = palette.red },
    PreProc { Constant },
    Include { Constant },
    Define { Constant },
    Macro { Constant },
    PreCondit { Constant },
    Type { fg = palette.orange },
    StorageClass { fg = palette.magenta },
    Structure { StorageClass },
    Typedef { Type },
    Special { fg = palette.subtle_white },
    SpecialChar { fg = palette.orange },
    Tag { fg = palette.orange },
    Delimiter { fg = palette.subtle_white },
    SpecialComment { fg = palette.orange },
    Debug { fg = palette.orange },
    Underlined { gui = "underline" },
    Ignore { fg = palette.gray },
    Error { fg = palette.red },
    Todo { bold = true, italic = true, fg = palette.yellow },

    -- LSP highlight groups (see :h lsp-highlight)
    LspReferenceText { bg = palette.subtle_yellow },
    LspReferenceRead { LspReferenceText },
    LspReferenceWrite { LspReferenceText },
    LspInlayHint { fg = palette.gray },
    LspCodeLens { LspInlayHint },
    LspCodeLensSeparator { LspInlayHint },
    LspSignatureActiveParameter { LspReferenceText },

    -- Diagnostic highlight groups (see :h diagnostic-highlights)
    DiagnosticError { fg = palette.red },
    DiagnosticWarn { fg = palette.yellow },
    DiagnosticInfo { fg = palette.blue },
    DiagnosticHint { fg = palette.blue },
    DiagnosticOk { fg = palette.subtle_green },
    DiagnosticVirtualTextError { DiagnosticError },
    DiagnosticVirtualTextWarn { DiagnosticWarn },
    DiagnosticVirtualTextInfo { DiagnosticInfo },
    DiagnosticVirtualTextHint { DiagnosticHint },
    DiagnosticVirtualTextOk { DiagnosticOk },
    DiagnosticUnderlineError { sp = palette.red, gui = "undercurl" },
    DiagnosticUnderlineWarn { sp = palette.yellow, gui = "undercurl" },
    DiagnosticUnderlineInfo { sp = palette.blue, gui = "undercurl" },
    DiagnosticUnderlineHint { sp = palette.blue, gui = "undercurl" },
    DiagnosticUnderlineOk { sp = palette.subtle_green, gui = "undercurl" },
    DiagnosticFloatingError { DiagnosticError },
    DiagnosticFloatingWarn { DiagnosticWarn },
    DiagnosticFloatingInfo { DiagnosticInfo },
    DiagnosticFloatingHint { DiagnosticHint },
    DiagnosticFloatingOk { DiagnosticOk },
    DiagnosticSignError { DiagnosticError },
    DiagnosticSignWarn { DiagnosticWarn },
    DiagnosticSignInfo { DiagnosticInfo },
    DiagnosticSignHint { DiagnosticHint },
    DiagnosticSignOk { DiagnosticOk },
    DiagnosticDeprecated { gui = "strikethrough" },
    DiagnosticUnnecessary { fg = palette.gray },

    -- Tree-Sitter highlight groups (see :h treesitter-highlight-groups)
    sym("@comment.todo") { Todo },
    sym("@comment") { Comment },
    sym("@lsp.type.comment") { gui = "italic" },
    sym("@punctuation") { Delimiter },
    sym("@constant") { Constant },
    sym("@constant.builtin") { Special },
    sym("@constant.macro") { Define },
    sym("@define") { Define },
    sym("@macro") { Macro },
    sym("@string") { String },
    sym("@string.escape") { SpecialChar },
    sym("@string.special") { SpecialChar },
    sym("@character") { Character },
    sym("@character.special") { SpecialChar },
    sym("@number") { Number },
    sym("@boolean") { Boolean },
    sym("@float") { Float },
    sym("@function") { Function },
    sym("@function.builtin") { Special },
    sym("@function.macro") { Macro },
    sym("@parameter") { fg = palette.subtle_white },
    sym("@method") { Function },
    sym("@field") { Identifier },
    sym("@property") { Identifier },
    sym("@constructor") { Special },
    sym("@conditional") { Conditional },
    sym("@repeat") { Repeat },
    sym("@label") { Label },
    sym("@operator") { Operator },
    sym("@keyword") { Keyword, gui = 'bold' },
    sym("@exception") { Exception },
    sym("@variable") { fg = palette.subtle_white },
    sym("@variable.parameter") { Identifier },
    sym("@variable.member") { Identifier },
    sym("@variable.builtin") { Keyword },
    sym("@variable.parameter.builtin") { Keyword },
    sym("@type") { Type },
    sym("@type.definition") { Typedef },
    sym("@storageclass") { StorageClass },
    sym("@structure") { Structure },
    sym("@namespace") { Identifier },
    sym("@include") { Include },
    sym("@preproc") { PreProc },
    sym("@debug") { Debug },
    sym("@tag") { Tag },
    sym("@tag.builtin") { Tag },

    -- Other highlight groups
    gitcommitSummary { fg = palette.subtle_white },
  }
end)
