local colors = {
  -- PATCH_OPEN
  Normal = { fg = "#CED1D4", bg = "#262627" },
  NormalNC = { link = "Normal" },
  Special = { link = "Normal" },
  ColorColumn = { bg = "#313235" },
  Comment = { fg = "#8A8A8A", italic = true },
  Constant = { fg = "#CD7832" },
  Boolean = { link = "Constant" },
  Character = { link = "Constant" },
  Conditional = { link = "Constant" },
  Debug = { link = "Constant" },
  Define = { link = "Constant" },
  Delimiter = { link = "Constant" },
  Include = { link = "Constant" },
  Keyword = { link = "Constant" },
  Label = { link = "Constant" },
  Macro = { link = "Constant" },
  PreCondit = { link = "Constant" },
  PreProc = { link = "Constant" },
  Repeat = { link = "Constant" },
  SpecialComment = { link = "Constant" },
  Statement = { link = "Constant" },
  CurSearch = { fg = "#262627", bg = "#FFC66B" },
  IncSearch = { link = "CurSearch" },
  Search = { link = "CurSearch" },
  Substitute = { link = "CurSearch" },
  Cursor = { fg = "#262627", bg = "#F7F7F7" },
  CursorColumn = { bg = "#313235" },
  CursorLine = { link = "CursorColumn" },
  CursorLineNr = { fg = "#CD7832" },
  DiffAdd = { fg = "#8FA867" },
  DiffChange = { fg = "#FFC66B" },
  DiffDelete = { fg = "#E74946" },
  DiffText = { fg = "#FFC66B", underline = true },
  Directory = { fg = "#87949B" },
  Error = { fg = "#E74946" },
  ErrorMsg = { fg = "#E74946" },
  Exception = { fg = "#E74946" },
  FloatTitle = { fg = "#CED1D4", bg = "#262627", bold = true },
  FoldColumn = { fg = "#585E65" },
  SignColumn = { link = "FoldColumn" },
  Folded = { fg = "#8A8A8A", bg = "#313235" },
  Function = { fg = "#FFC66B" },
  Identifier = { fg = "#FFC66B" },
  Ignore = { fg = "#585E65" },
  LineNr = { fg = "#585E65" },
  LspReferenceText = { bg = "#313235" },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  MatchParen = { fg = "#F7F7F7", bg = "#313235" },
  ModeMsg = { fg = "#585E65" },
  MoreMsg = { fg = "#8FA867" },
  MsgArea = { fg = "#CED1D4", bg = "#262627" },
  MsgSeparator = { fg = "#CD7832" },
  NonText = { fg = "#CED1D4", bg = "#262627" },
  NormalFloat = { link = "NonText" },
  Number = { fg = "#83B1F1" },
  Float = { link = "Number" },
  Operator = { fg = "#CED1D4" },
  Pmenu = { fg = "#CED1D4", bg = "#313235" },
  PmenuExtra = { link = "Pmenu" },
  PmenuKind = { link = "Pmenu" },
  WildMenu = { link = "Pmenu" },
  PmenuSbar = { fg = "#262627", bg = "#CED1D4" },
  PmenuThumb = { link = "PmenuSbar" },
  PmenuSel = { bg = "#585E65", bold = true },
  PmenuExtraSel = { link = "PmenuSel" },
  PmenuKindSel = { link = "PmenuSel" },
  TabLineSel = { link = "PmenuSel" },
  Question = { fg = "#8FA867" },
  QuickFixLine = { fg = "#F7F7F7" },
  SpecialChar = { fg = "#CD7832" },
  SpellBad = { undercurl = true },
  SpellCap = { fg = "#D194C7", underline = true },
  SpellLocal = { fg = "#CD7832", underline = true },
  SpellRare = { fg = "#FFC66B", underline = true },
  StatusLine = { bg = "#313235" },
  StatusLineNC = { link = "StatusLine" },
  TabLine = { link = "StatusLine" },
  TabLineFill = { link = "StatusLine" },
  StorageClass = { fg = "#D194C7" },
  Structure = { link = "StorageClass" },
  String = { fg = "#8FA867" },
  Tag = { fg = "#FFC66B" },
  TermCursor = { fg = "#262627", bg = "#F7F7F7" },
  Title = { fg = "#83B1F1" },
  Todo = { bold = true },
  Type = { fg = "#CD7832" },
  Typedef = { link = "Type" },
  Underlined = { underline = true },
  VertSplit = { fg = "#585E65", bg = "#262627" },
  FloatBorder = { link = "VertSplit" },
  Winseparator = { link = "VertSplit" },
  Visual = { fg = "#F7F7F7", bg = "#83B1F1" },
  VisualNOS = { link = "Visual" },
  WarningMsg = { fg = "#E74946" },
  -- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='darcula-solid'")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
