local colors = {
  -- PATCH_OPEN
  Normal = { fg = "#CED1D4", bg = "#262627" },
  NormalNC = { link = "Normal" },
  ["@boolean"] = { link = "Boolean" },
  ["@character"] = { link = "Character" },
  ColorColumn = { bg = "#313235" },
  Comment = { fg = "#8A8A8A", italic = true },
  ["@comment"] = { link = "Comment" },
  Conceal = { fg = "#585E65" },
  EndOfBuffer = { link = "Conceal" },
  SpecialKey = { link = "Conceal" },
  Whitespace = { link = "Conceal" },
  ["@conditional"] = { link = "Conditional" },
  Constant = { fg = "#CD7832" },
  Boolean = { link = "Constant" },
  Character = { link = "Constant" },
  Conditional = { link = "Constant" },
  Define = { link = "Constant" },
  Include = { link = "Constant" },
  Keyword = { link = "Constant" },
  Label = { link = "Constant" },
  Macro = { link = "Constant" },
  PreCondit = { link = "Constant" },
  PreProc = { link = "Constant" },
  Repeat = { link = "Constant" },
  Statement = { link = "Constant" },
  ["@constant"] = { link = "Constant" },
  CurSearch = { bg = "#32583C" },
  IncSearch = { link = "CurSearch" },
  Search = { link = "CurSearch" },
  Substitute = { link = "CurSearch" },
  Cursor = { fg = "#262627", bg = "#F7F7F7" },
  CursorIM = { link = "Cursor" },
  TermCursor = { link = "Cursor" },
  TermCursorNC = { link = "Cursor" },
  lCursor = { link = "Cursor" },
  CursorColumn = { bg = "#313235" },
  CursorLine = { link = "CursorColumn" },
  CursorLineNr = { fg = "#CD7832" },
  Debug = { fg = "#CD7832" },
  ["@debug"] = { link = "Debug" },
  ["@constant.macro"] = { link = "Define" },
  ["@define"] = { link = "Define" },
  Delimiter = { fg = "#CED1D4" },
  ["@punctuation"] = { link = "Delimiter" },
  DiagnosticDeprecated = { strikethrough = true },
  DiagnosticError = { fg = "#E74946" },
  DiagnosticFloatingError = { link = "DiagnosticError" },
  DiagnosticSignError = { link = "DiagnosticError" },
  DiagnosticVirtualTextError = { link = "DiagnosticError" },
  DiagnosticHint = { fg = "#83B1F1" },
  DiagnosticFloatingHint = { link = "DiagnosticHint" },
  DiagnosticSignHint = { link = "DiagnosticHint" },
  DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
  DiagnosticInfo = { fg = "#83B1F1" },
  DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
  DiagnosticSignInfo = { link = "DiagnosticInfo" },
  DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
  DiagnosticOk = { fg = "#8CA664" },
  DiagnosticFloatingOk = { link = "DiagnosticOk" },
  DiagnosticSignOk = { link = "DiagnosticOk" },
  DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
  DiagnosticUnderlineError = { sp = "#E74946", undercurl = true },
  DiagnosticUnderlineHint = { sp = "#83B1F1", undercurl = true },
  DiagnosticUnderlineInfo = { sp = "#83B1F1", undercurl = true },
  DiagnosticUnderlineOk = { sp = "#8CA664", undercurl = true },
  DiagnosticUnderlineWarn = { sp = "#FFC66B", undercurl = true },
  DiagnosticUnnecessary = { fg = "#585E65" },
  DiagnosticWarn = { fg = "#FFC66B" },
  DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
  DiagnosticSignWarn = { link = "DiagnosticWarn" },
  DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
  DiffAdd = { bg = "#32583C" },
  DiffChange = { bg = "#514F39" },
  DiffDelete = { bg = "#E74946" },
  DiffText = { bg = "#27333F" },
  DiffTextChange = { bg = "#27333F" },
  Directory = { fg = "#87949B" },
  Error = { fg = "#E74946" },
  ErrorMsg = { fg = "#E74946" },
  Exception = { fg = "#E74946" },
  ["@exception"] = { link = "Exception" },
  ["@float"] = { link = "Float" },
  FloatBorder = { fg = "#8A8A8A", bg = "#313235" },
  FloatTitle = { bold = true },
  FoldColumn = { fg = "#585E65" },
  SignColumn = { link = "FoldColumn" },
  Folded = { fg = "#8A8A8A", bg = "#313235" },
  Function = { fg = "#FFC66B" },
  ["@function"] = { link = "Function" },
  ["@method"] = { link = "Function" },
  Identifier = { fg = "#FFC66B" },
  ["@field"] = { link = "Identifier" },
  ["@namespace"] = { link = "Identifier" },
  ["@property"] = { link = "Identifier" },
  ["@variable.member"] = { link = "Identifier" },
  ["@variable.parameter"] = { link = "Identifier" },
  Ignore = { fg = "#585E65" },
  ["@include"] = { link = "Include" },
  ["@variable.builtin"] = { link = "Keyword" },
  ["@variable.parameter.builtin"] = { link = "Keyword" },
  ["@label"] = { link = "Label" },
  LineNr = { fg = "#585E65" },
  CursorLineFold = { link = "LineNr" },
  CursorLineSign = { link = "LineNr" },
  LineNrAbove = { link = "LineNr" },
  LineNrBelow = { link = "LineNr" },
  LspInlayHint = { fg = "#585E65" },
  LspCodeLens = { link = "LspInlayHint" },
  LspCodeLensSeparator = { link = "LspInlayHint" },
  LspReferenceText = { bg = "#514F39" },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspSignatureActiveParameter = { link = "LspReferenceText" },
  ["@function.macro"] = { link = "Macro" },
  ["@macro"] = { link = "Macro" },
  MatchParen = { fg = "#F7F7F7", bg = "#313235" },
  ModeMsg = { fg = "#585E65" },
  MoreMsg = { fg = "#8CA664" },
  MsgArea = { bg = "#313235" },
  MsgSeparator = { fg = "#CD7832" },
  NonText = { bg = "#313235" },
  NormalFloat = { bg = "#313235" },
  Number = { fg = "#83B1F1" },
  Float = { link = "Number" },
  ["@number"] = { link = "Number" },
  Operator = { fg = "#CED1D4" },
  ["@operator"] = { link = "Operator" },
  Pmenu = { bg = "#313235" },
  PmenuExtra = { link = "Pmenu" },
  PmenuKind = { link = "Pmenu" },
  WildMenu = { link = "Pmenu" },
  PmenuSbar = { fg = "#262627", bg = "#CED1D4" },
  PmenuThumb = { link = "PmenuSbar" },
  PmenuSel = { bg = "#585E65", bold = true },
  PmenuExtraSel = { link = "PmenuSel" },
  PmenuKindSel = { link = "PmenuSel" },
  TabLineSel = { link = "PmenuSel" },
  ["@preproc"] = { link = "PreProc" },
  Question = { fg = "#8CA664" },
  QuickFixLine = { fg = "#F7F7F7" },
  ["@repeat"] = { link = "Repeat" },
  Special = { fg = "#CED1D4" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constructor"] = { link = "Special" },
  ["@function.builtin"] = { link = "Special" },
  SpecialChar = { fg = "#CD7832" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@string.escape"] = { link = "SpecialChar" },
  ["@string.special"] = { link = "SpecialChar" },
  SpecialComment = { fg = "#CD7832" },
  SpellBad = { sp = "#E74946", undercurl = true },
  SpellCap = { sp = "#D194C7", undercurl = true },
  SpellLocal = { sp = "#CD7832", undercurl = true },
  SpellRare = { sp = "#FFC66B", undercurl = true },
  StatusLine = { bg = "#313235" },
  StatusLineNC = { link = "StatusLine" },
  TabLine = { link = "StatusLine" },
  TabLineFill = { link = "StatusLine" },
  StorageClass = { fg = "#D194C7" },
  Structure = { link = "StorageClass" },
  ["@storageclass"] = { link = "StorageClass" },
  String = { fg = "#8CA664" },
  ["@string"] = { link = "String" },
  ["@structure"] = { link = "Structure" },
  Tag = { fg = "#CD7832" },
  ["@tag"] = { link = "Tag" },
  ["@tag.builtin"] = { link = "Tag" },
  Title = { fg = "#83B1F1" },
  Todo = { fg = "#FFC66B", bold = true, italic = true },
  ["@comment.todo"] = { link = "Todo" },
  Type = { fg = "#CD7832" },
  Typedef = { link = "Type" },
  ["@type"] = { link = "Type" },
  ["@type.definition"] = { link = "Typedef" },
  Underlined = { underline = true },
  VertSplit = { fg = "#8A8A8A" },
  Winseparator = { link = "VertSplit" },
  Visual = { fg = "#F7F7F7", bg = "#83B1F1" },
  VisualNOS = { link = "Visual" },
  WarningMsg = { fg = "#E74946" },
  WinBar = { fg = "#585E65", bg = "#313235" },
  WinBarNC = { link = "WinBar" },
  gitcommitSummary = { fg = "#CED1D4" },
  ["@keyword"] = { fg = "#CD7832", bold = true },
  ["@lsp.type.comment"] = { italic = true },
  ["@parameter"] = { fg = "#CED1D4" },
  ["@variable"] = { fg = "#CED1D4" },
  -- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='darcula-solid'")

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
